CREATE TABLE IF NOT EXISTS `Netflixo_youtube_movies` (
    `id_oid` VARCHAR(24) CHARACTER SET utf8,
    `name` VARCHAR(29) CHARACTER SET utf8,
    `image` VARCHAR(32) CHARACTER SET utf8,
    `year` INT,
    `genre_oid` VARCHAR(24) CHARACTER SET utf8,
    `detail` VARCHAR(1052) CHARACTER SET utf8,
    `cast` VARCHAR(18) CHARACTER SET utf8,
    `numReviews` INT,
    `reviews` VARCHAR(2) CHARACTER SET utf8,
    `createdAt_date` VARCHAR(24) CHARACTER SET utf8,
    `updatedAt_date` VARCHAR(24) CHARACTER SET utf8,
    `v` INT,
    `reviews_name` VARCHAR(13) CHARACTER SET utf8,
    `reviews_rating` INT,
    `reviews_comment` VARCHAR(20) CHARACTER SET utf8,
    `reviews_user_oid` VARCHAR(24) CHARACTER SET utf8,
    `reviews_id_oid` VARCHAR(24) CHARACTER SET utf8,
    `reviews_createdAt_date` VARCHAR(24) CHARACTER SET utf8,
    `reviews_updatedAt_date` VARCHAR(24) CHARACTER SET utf8
);
INSERT INTO `Netflixo_youtube_movies` VALUES ('6778004da63ae07a43d1dcae',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Moana','/uploads\\image-1735922920632.jpg',2024,'6777fb0bbc3162bf784c367c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Moana','/uploads\\image-1735922920632.jpg',2024,NULL,'Film Moana 2 adalah sekuel dari film animasi Disney "Moana" yang dirilis pada tahun 2016. Film ini melanjutkan petualangan Moana, yang kini berusia 21 tahun, saat ia menerima panggilan tak terduga dari leluhur penjelajahnya. Panggilan ini membawanya dalam perjalanan ke lautan jauh di Oceania untuk menemukan pulau yang hilang, Motufetū','Dwayne Johnson',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Moana','/uploads\\image-1735922920632.jpg',2024,NULL,'Film Moana 2 adalah sekuel dari film animasi Disney "Moana" yang dirilis pada tahun 2016. Film ini melanjutkan petualangan Moana, yang kini berusia 21 tahun, saat ia menerima panggilan tak terduga dari leluhur penjelajahnya. Panggilan ini membawanya dalam perjalanan ke lautan jauh di Oceania untuk menemukan pulau yang hilang, Motufetū','Auli''i Cravalho',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Moana','/uploads\\image-1735922920632.jpg',2024,NULL,'Film Moana 2 adalah sekuel dari film animasi Disney "Moana" yang dirilis pada tahun 2016. Film ini melanjutkan petualangan Moana, yang kini berusia 21 tahun, saat ia menerima panggilan tak terduga dari leluhur penjelajahnya. Panggilan ini membawanya dalam perjalanan ke lautan jauh di Oceania untuk menemukan pulau yang hilang, Motufetū',NULL,0,'[]','2025-01-03T15:20:45.681Z',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Moana','/uploads\\image-1735922920632.jpg',2024,NULL,'Film Moana 2 adalah sekuel dari film animasi Disney "Moana" yang dirilis pada tahun 2016. Film ini melanjutkan petualangan Moana, yang kini berusia 21 tahun, saat ia menerima panggilan tak terduga dari leluhur penjelajahnya. Panggilan ini membawanya dalam perjalanan ke lautan jauh di Oceania untuk menemukan pulau yang hilang, Motufetū',NULL,0,'[]',NULL,'2025-01-21T02:58:31.523Z',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Moana','/uploads\\image-1735922920632.jpg',2024,NULL,'Film Moana 2 adalah sekuel dari film animasi Disney "Moana" yang dirilis pada tahun 2016. Film ini melanjutkan petualangan Moana, yang kini berusia 21 tahun, saat ia menerima panggilan tak terduga dari leluhur penjelajahnya. Panggilan ini membawanya dalam perjalanan ke lautan jauh di Oceania untuk menemukan pulau yang hilang, Motufetū',NULL,0,'[]',NULL,NULL,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('677802e8a63ae07a43d1dce2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,'6777fb0bbc3162bf784c367c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,NULL,'Film Titanic adalah film drama romantis epik yang disutradarai oleh James Cameron. Ceritanya mengikuti kisah cinta antara Jack Dawson (diperankan oleh Leonardo DiCaprio), seorang pemuda miskin yang menang lotre untuk naik kapal pesiar Titanic, dan Rose DeWitt Bukater (diperankan oleh Kate Winslet), seorang wanita muda dari keluarga kaya yang terikat pada tunangannya, Cal Hockley (diperankan oleh Billy Zane).

Pada tahun 1912, Titanic, kapal terbesar dan termewah yang pernah dibangun, berlayar dalam pelayaran perdananya dari Southampton menuju New York. Selama perjalanan, Rose, yang merasa terjebak dalam kehidupan sosial yang ketat dan pernikahan yang tidak diinginkan, bertemu dengan Jack. Mereka mulai menjalin hubungan yang rumit meskipun perbedaan kelas sosial yang besar.

Namun, perjalanan indah mereka terganggu oleh tragedi besar. Kapal Titanic menabrak gunung es dan mulai tenggelam ke dasar laut. Kejadian ini memicu kekacauan di atas kapal, dan Rose serta Jack berjuang untuk bertahan hidup dalam menghadapi peristiwa yang mengerikan.','Leonardo DiCaprio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,NULL,'Film Titanic adalah film drama romantis epik yang disutradarai oleh James Cameron. Ceritanya mengikuti kisah cinta antara Jack Dawson (diperankan oleh Leonardo DiCaprio), seorang pemuda miskin yang menang lotre untuk naik kapal pesiar Titanic, dan Rose DeWitt Bukater (diperankan oleh Kate Winslet), seorang wanita muda dari keluarga kaya yang terikat pada tunangannya, Cal Hockley (diperankan oleh Billy Zane).

Pada tahun 1912, Titanic, kapal terbesar dan termewah yang pernah dibangun, berlayar dalam pelayaran perdananya dari Southampton menuju New York. Selama perjalanan, Rose, yang merasa terjebak dalam kehidupan sosial yang ketat dan pernikahan yang tidak diinginkan, bertemu dengan Jack. Mereka mulai menjalin hubungan yang rumit meskipun perbedaan kelas sosial yang besar.

Namun, perjalanan indah mereka terganggu oleh tragedi besar. Kapal Titanic menabrak gunung es dan mulai tenggelam ke dasar laut. Kejadian ini memicu kekacauan di atas kapal, dan Rose serta Jack berjuang untuk bertahan hidup dalam menghadapi peristiwa yang mengerikan.','Kate Winslet',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,NULL,'Film Titanic adalah film drama romantis epik yang disutradarai oleh James Cameron. Ceritanya mengikuti kisah cinta antara Jack Dawson (diperankan oleh Leonardo DiCaprio), seorang pemuda miskin yang menang lotre untuk naik kapal pesiar Titanic, dan Rose DeWitt Bukater (diperankan oleh Kate Winslet), seorang wanita muda dari keluarga kaya yang terikat pada tunangannya, Cal Hockley (diperankan oleh Billy Zane).

Pada tahun 1912, Titanic, kapal terbesar dan termewah yang pernah dibangun, berlayar dalam pelayaran perdananya dari Southampton menuju New York. Selama perjalanan, Rose, yang merasa terjebak dalam kehidupan sosial yang ketat dan pernikahan yang tidak diinginkan, bertemu dengan Jack. Mereka mulai menjalin hubungan yang rumit meskipun perbedaan kelas sosial yang besar.

Namun, perjalanan indah mereka terganggu oleh tragedi besar. Kapal Titanic menabrak gunung es dan mulai tenggelam ke dasar laut. Kejadian ini memicu kekacauan di atas kapal, dan Rose serta Jack berjuang untuk bertahan hidup dalam menghadapi peristiwa yang mengerikan.',NULL,1,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus','677808807e8e51503fb9e8ab',NULL,NULL,NULL),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,NULL,'Film Titanic adalah film drama romantis epik yang disutradarai oleh James Cameron. Ceritanya mengikuti kisah cinta antara Jack Dawson (diperankan oleh Leonardo DiCaprio), seorang pemuda miskin yang menang lotre untuk naik kapal pesiar Titanic, dan Rose DeWitt Bukater (diperankan oleh Kate Winslet), seorang wanita muda dari keluarga kaya yang terikat pada tunangannya, Cal Hockley (diperankan oleh Billy Zane).

Pada tahun 1912, Titanic, kapal terbesar dan termewah yang pernah dibangun, berlayar dalam pelayaran perdananya dari Southampton menuju New York. Selama perjalanan, Rose, yang merasa terjebak dalam kehidupan sosial yang ketat dan pernikahan yang tidak diinginkan, bertemu dengan Jack. Mereka mulai menjalin hubungan yang rumit meskipun perbedaan kelas sosial yang besar.

Namun, perjalanan indah mereka terganggu oleh tragedi besar. Kapal Titanic menabrak gunung es dan mulai tenggelam ke dasar laut. Kejadian ini memicu kekacauan di atas kapal, dan Rose serta Jack berjuang untuk bertahan hidup dalam menghadapi peristiwa yang mengerikan.',NULL,1,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus',NULL,'6778097e7e8e51503fb9e8c4',NULL,NULL),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,NULL,'Film Titanic adalah film drama romantis epik yang disutradarai oleh James Cameron. Ceritanya mengikuti kisah cinta antara Jack Dawson (diperankan oleh Leonardo DiCaprio), seorang pemuda miskin yang menang lotre untuk naik kapal pesiar Titanic, dan Rose DeWitt Bukater (diperankan oleh Kate Winslet), seorang wanita muda dari keluarga kaya yang terikat pada tunangannya, Cal Hockley (diperankan oleh Billy Zane).

Pada tahun 1912, Titanic, kapal terbesar dan termewah yang pernah dibangun, berlayar dalam pelayaran perdananya dari Southampton menuju New York. Selama perjalanan, Rose, yang merasa terjebak dalam kehidupan sosial yang ketat dan pernikahan yang tidak diinginkan, bertemu dengan Jack. Mereka mulai menjalin hubungan yang rumit meskipun perbedaan kelas sosial yang besar.

Namun, perjalanan indah mereka terganggu oleh tragedi besar. Kapal Titanic menabrak gunung es dan mulai tenggelam ke dasar laut. Kejadian ini memicu kekacauan di atas kapal, dan Rose serta Jack berjuang untuk bertahan hidup dalam menghadapi peristiwa yang mengerikan.',NULL,1,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,'2025-01-03T16:50:58.936Z',NULL),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,NULL,'Film Titanic adalah film drama romantis epik yang disutradarai oleh James Cameron. Ceritanya mengikuti kisah cinta antara Jack Dawson (diperankan oleh Leonardo DiCaprio), seorang pemuda miskin yang menang lotre untuk naik kapal pesiar Titanic, dan Rose DeWitt Bukater (diperankan oleh Kate Winslet), seorang wanita muda dari keluarga kaya yang terikat pada tunangannya, Cal Hockley (diperankan oleh Billy Zane).

Pada tahun 1912, Titanic, kapal terbesar dan termewah yang pernah dibangun, berlayar dalam pelayaran perdananya dari Southampton menuju New York. Selama perjalanan, Rose, yang merasa terjebak dalam kehidupan sosial yang ketat dan pernikahan yang tidak diinginkan, bertemu dengan Jack. Mereka mulai menjalin hubungan yang rumit meskipun perbedaan kelas sosial yang besar.

Namun, perjalanan indah mereka terganggu oleh tragedi besar. Kapal Titanic menabrak gunung es dan mulai tenggelam ke dasar laut. Kejadian ini memicu kekacauan di atas kapal, dan Rose serta Jack berjuang untuk bertahan hidup dalam menghadapi peristiwa yang mengerikan.',NULL,1,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,'2025-01-03T16:50:58.936Z'),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,NULL,'Film Titanic adalah film drama romantis epik yang disutradarai oleh James Cameron. Ceritanya mengikuti kisah cinta antara Jack Dawson (diperankan oleh Leonardo DiCaprio), seorang pemuda miskin yang menang lotre untuk naik kapal pesiar Titanic, dan Rose DeWitt Bukater (diperankan oleh Kate Winslet), seorang wanita muda dari keluarga kaya yang terikat pada tunangannya, Cal Hockley (diperankan oleh Billy Zane).

Pada tahun 1912, Titanic, kapal terbesar dan termewah yang pernah dibangun, berlayar dalam pelayaran perdananya dari Southampton menuju New York. Selama perjalanan, Rose, yang merasa terjebak dalam kehidupan sosial yang ketat dan pernikahan yang tidak diinginkan, bertemu dengan Jack. Mereka mulai menjalin hubungan yang rumit meskipun perbedaan kelas sosial yang besar.

Namun, perjalanan indah mereka terganggu oleh tragedi besar. Kapal Titanic menabrak gunung es dan mulai tenggelam ke dasar laut. Kejadian ini memicu kekacauan di atas kapal, dan Rose serta Jack berjuang untuk bertahan hidup dalam menghadapi peristiwa yang mengerikan.',NULL,1,NULL,'2025-01-03T15:31:52.367Z',NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,NULL,'Film Titanic adalah film drama romantis epik yang disutradarai oleh James Cameron. Ceritanya mengikuti kisah cinta antara Jack Dawson (diperankan oleh Leonardo DiCaprio), seorang pemuda miskin yang menang lotre untuk naik kapal pesiar Titanic, dan Rose DeWitt Bukater (diperankan oleh Kate Winslet), seorang wanita muda dari keluarga kaya yang terikat pada tunangannya, Cal Hockley (diperankan oleh Billy Zane).

Pada tahun 1912, Titanic, kapal terbesar dan termewah yang pernah dibangun, berlayar dalam pelayaran perdananya dari Southampton menuju New York. Selama perjalanan, Rose, yang merasa terjebak dalam kehidupan sosial yang ketat dan pernikahan yang tidak diinginkan, bertemu dengan Jack. Mereka mulai menjalin hubungan yang rumit meskipun perbedaan kelas sosial yang besar.

Namun, perjalanan indah mereka terganggu oleh tragedi besar. Kapal Titanic menabrak gunung es dan mulai tenggelam ke dasar laut. Kejadian ini memicu kekacauan di atas kapal, dan Rose serta Jack berjuang untuk bertahan hidup dalam menghadapi peristiwa yang mengerikan.',NULL,1,NULL,NULL,'2025-01-03T16:50:58.936Z',NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'Titanic','/uploads\\image-1735918312017.jpg',1997,NULL,'Film Titanic adalah film drama romantis epik yang disutradarai oleh James Cameron. Ceritanya mengikuti kisah cinta antara Jack Dawson (diperankan oleh Leonardo DiCaprio), seorang pemuda miskin yang menang lotre untuk naik kapal pesiar Titanic, dan Rose DeWitt Bukater (diperankan oleh Kate Winslet), seorang wanita muda dari keluarga kaya yang terikat pada tunangannya, Cal Hockley (diperankan oleh Billy Zane).

Pada tahun 1912, Titanic, kapal terbesar dan termewah yang pernah dibangun, berlayar dalam pelayaran perdananya dari Southampton menuju New York. Selama perjalanan, Rose, yang merasa terjebak dalam kehidupan sosial yang ketat dan pernikahan yang tidak diinginkan, bertemu dengan Jack. Mereka mulai menjalin hubungan yang rumit meskipun perbedaan kelas sosial yang besar.

Namun, perjalanan indah mereka terganggu oleh tragedi besar. Kapal Titanic menabrak gunung es dan mulai tenggelam ke dasar laut. Kejadian ini memicu kekacauan di atas kapal, dan Rose serta Jack berjuang untuk bertahan hidup dalam menghadapi peristiwa yang mengerikan.',NULL,1,NULL,NULL,NULL,1,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	('67780e3b7e8e51503fb9e8eb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'Avenger: End Game','/uploads\\image-1735921210906.jpg',2019,'6777fb0bbc3162bf784c367c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'Avenger: End Game','/uploads\\image-1735921210906.jpg',2019,NULL,'Marvel','Tonny Stark',NULL,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'Avenger: End Game','/uploads\\image-1735921210906.jpg',2019,NULL,'Marvel',NULL,0,'[]','2025-01-03T16:20:11.033Z',NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'Avenger: End Game','/uploads\\image-1735921210906.jpg',2019,NULL,'Marvel',NULL,0,'[]',NULL,'2025-01-03T16:20:11.033Z',NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'Avenger: End Game','/uploads\\image-1735921210906.jpg',2019,NULL,'Marvel',NULL,0,'[]',NULL,NULL,0,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	('67780f717e8e51503fb9e91e',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring 2','/uploads\\image-1735921520754.jpg',2016,'6777f96abc3162bf784c3659',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring 2','/uploads\\image-1735921520754.jpg',2016,NULL,'The Conjuring 2 disutradarai oleh James Wan dan dibintangi oleh Patrick Wilson dan Vera Farmiga. Film ini diangkat dari kisah nyata yang dialami keluarga Hodgson di Inggris, yang dikenal sebagai Enfield Poltergeist. ','James Wan',NULL,NULL,NULL,NULL,NULL,'haris',0,'film nya bagus',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring 2','/uploads\\image-1735921520754.jpg',2016,NULL,'The Conjuring 2 disutradarai oleh James Wan dan dibintangi oleh Patrick Wilson dan Vera Farmiga. Film ini diangkat dari kisah nyata yang dialami keluarga Hodgson di Inggris, yang dikenal sebagai Enfield Poltergeist. ',NULL,1,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget','6777f5f5bc3162bf784c3646',NULL,NULL,NULL),
	(NULL,'The Conjuring 2','/uploads\\image-1735921520754.jpg',2016,NULL,'The Conjuring 2 disutradarai oleh James Wan dan dibintangi oleh Patrick Wilson dan Vera Farmiga. Film ini diangkat dari kisah nyata yang dialami keluarga Hodgson di Inggris, yang dikenal sebagai Enfield Poltergeist. ',NULL,1,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,'677810107e8e51503fb9e933',NULL,NULL),
	(NULL,'The Conjuring 2','/uploads\\image-1735921520754.jpg',2016,NULL,'The Conjuring 2 disutradarai oleh James Wan dan dibintangi oleh Patrick Wilson dan Vera Farmiga. Film ini diangkat dari kisah nyata yang dialami keluarga Hodgson di Inggris, yang dikenal sebagai Enfield Poltergeist. ',NULL,1,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,'2025-01-03T16:28:00.623Z',NULL),
	(NULL,'The Conjuring 2','/uploads\\image-1735921520754.jpg',2016,NULL,'The Conjuring 2 disutradarai oleh James Wan dan dibintangi oleh Patrick Wilson dan Vera Farmiga. Film ini diangkat dari kisah nyata yang dialami keluarga Hodgson di Inggris, yang dikenal sebagai Enfield Poltergeist. ',NULL,1,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,'2025-01-03T16:28:00.623Z'),
	(NULL,'The Conjuring 2','/uploads\\image-1735921520754.jpg',2016,NULL,'The Conjuring 2 disutradarai oleh James Wan dan dibintangi oleh Patrick Wilson dan Vera Farmiga. Film ini diangkat dari kisah nyata yang dialami keluarga Hodgson di Inggris, yang dikenal sebagai Enfield Poltergeist. ',NULL,1,NULL,'2025-01-03T16:25:21.187Z',NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring 2','/uploads\\image-1735921520754.jpg',2016,NULL,'The Conjuring 2 disutradarai oleh James Wan dan dibintangi oleh Patrick Wilson dan Vera Farmiga. Film ini diangkat dari kisah nyata yang dialami keluarga Hodgson di Inggris, yang dikenal sebagai Enfield Poltergeist. ',NULL,1,NULL,NULL,'2025-01-03T16:28:00.624Z',NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring 2','/uploads\\image-1735921520754.jpg',2016,NULL,'The Conjuring 2 disutradarai oleh James Wan dan dibintangi oleh Patrick Wilson dan Vera Farmiga. Film ini diangkat dari kisah nyata yang dialami keluarga Hodgson di Inggris, yang dikenal sebagai Enfield Poltergeist. ',NULL,1,NULL,NULL,NULL,1,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	('677810f07e8e51503fb9e94b',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring ','/uploads\\image-1735921904281.jpg',2013,'6777f96abc3162bf784c3659',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring ','/uploads\\image-1735921904281.jpg',2013,NULL,'The Conjuring adalah film horor yang disutradarai oleh James Wan, yang didasarkan pada kisah nyata tentang pasangan penyelidik paranormal, Ed dan Lorraine Warren. Dalam cerita ini, keluarga Perron pindah ke sebuah rumah tua di Rhode Island, di mana mereka mulai mengalami fenomena aneh dan menakutkan. Seiring dengan berjalannya waktu, kejadian-kejadian gaib tersebut semakin menjadi-jadi dan mengancam keselamatan mereka. Keluarga Perron kemudian meminta bantuan dari Ed dan Lorraine Warren, yang menemukan bahwa rumah tersebut dihantui oleh entitas jahat yang sangat kuat.','James Wan',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring ','/uploads\\image-1735921904281.jpg',2013,NULL,'The Conjuring adalah film horor yang disutradarai oleh James Wan, yang didasarkan pada kisah nyata tentang pasangan penyelidik paranormal, Ed dan Lorraine Warren. Dalam cerita ini, keluarga Perron pindah ke sebuah rumah tua di Rhode Island, di mana mereka mulai mengalami fenomena aneh dan menakutkan. Seiring dengan berjalannya waktu, kejadian-kejadian gaib tersebut semakin menjadi-jadi dan mengancam keselamatan mereka. Keluarga Perron kemudian meminta bantuan dari Ed dan Lorraine Warren, yang menemukan bahwa rumah tersebut dihantui oleh entitas jahat yang sangat kuat.',NULL,0,'[]','2025-01-03T16:31:44.354Z',NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring ','/uploads\\image-1735921904281.jpg',2013,NULL,'The Conjuring adalah film horor yang disutradarai oleh James Wan, yang didasarkan pada kisah nyata tentang pasangan penyelidik paranormal, Ed dan Lorraine Warren. Dalam cerita ini, keluarga Perron pindah ke sebuah rumah tua di Rhode Island, di mana mereka mulai mengalami fenomena aneh dan menakutkan. Seiring dengan berjalannya waktu, kejadian-kejadian gaib tersebut semakin menjadi-jadi dan mengancam keselamatan mereka. Keluarga Perron kemudian meminta bantuan dari Ed dan Lorraine Warren, yang menemukan bahwa rumah tersebut dihantui oleh entitas jahat yang sangat kuat.',NULL,0,'[]',NULL,'2025-01-03T16:31:44.354Z',NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'The Conjuring ','/uploads\\image-1735921904281.jpg',2013,NULL,'The Conjuring adalah film horor yang disutradarai oleh James Wan, yang didasarkan pada kisah nyata tentang pasangan penyelidik paranormal, Ed dan Lorraine Warren. Dalam cerita ini, keluarga Perron pindah ke sebuah rumah tua di Rhode Island, di mana mereka mulai mengalami fenomena aneh dan menakutkan. Seiring dengan berjalannya waktu, kejadian-kejadian gaib tersebut semakin menjadi-jadi dan mengancam keselamatan mereka. Keluarga Perron kemudian meminta bantuan dari Ed dan Lorraine Warren, yang menemukan bahwa rumah tersebut dihantui oleh entitas jahat yang sangat kuat.',NULL,0,'[]',NULL,NULL,0,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	('677811b47e8e51503fb9e95a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'Joker','/uploads\\image-1735922100114.jpg',2019,'67780ea27e8e51503fb9e90f',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'Joker','/uploads\\image-1735922100114.jpg',2019,NULL,'Joker (2019), disutradarai oleh Todd Phillips, adalah sebuah film psikologis yang mengisahkan asal-usul karakter ikonik Joker, musuh bebuyutan Batman. Film ini berfokus pada Arthur Fleck, seorang pria yang bekerja sebagai badut dan bermimpi menjadi seorang komedian. Arthur hidup di Gotham City yang penuh dengan kesulitan dan ketidakadilan sosial. Ia mengalami kesulitan emosional dan psikologis yang berat, sementara masyarakat dan orang-orang di sekitarnya terus memperlakukan dirinya dengan hina.','Todd Phillips',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'Filmnya seram banget',NULL,NULL,NULL,NULL),
	(NULL,'Joker','/uploads\\image-1735922100114.jpg',2019,NULL,'Joker (2019), disutradarai oleh Todd Phillips, adalah sebuah film psikologis yang mengisahkan asal-usul karakter ikonik Joker, musuh bebuyutan Batman. Film ini berfokus pada Arthur Fleck, seorang pria yang bekerja sebagai badut dan bermimpi menjadi seorang komedian. Arthur hidup di Gotham City yang penuh dengan kesulitan dan ketidakadilan sosial. Ia mengalami kesulitan emosional dan psikologis yang berat, sementara masyarakat dan orang-orang di sekitarnya terus memperlakukan dirinya dengan hina.',NULL,1,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman','6777f5f5bc3162bf784c3646',NULL,NULL,NULL),
	(NULL,'Joker','/uploads\\image-1735922100114.jpg',2019,NULL,'Joker (2019), disutradarai oleh Todd Phillips, adalah sebuah film psikologis yang mengisahkan asal-usul karakter ikonik Joker, musuh bebuyutan Batman. Film ini berfokus pada Arthur Fleck, seorang pria yang bekerja sebagai badut dan bermimpi menjadi seorang komedian. Arthur hidup di Gotham City yang penuh dengan kesulitan dan ketidakadilan sosial. Ia mengalami kesulitan emosional dan psikologis yang berat, sementara masyarakat dan orang-orang di sekitarnya terus memperlakukan dirinya dengan hina.',NULL,1,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,'677811d27e8e51503fb9e969',NULL,NULL),
	(NULL,'Joker','/uploads\\image-1735922100114.jpg',2019,NULL,'Joker (2019), disutradarai oleh Todd Phillips, adalah sebuah film psikologis yang mengisahkan asal-usul karakter ikonik Joker, musuh bebuyutan Batman. Film ini berfokus pada Arthur Fleck, seorang pria yang bekerja sebagai badut dan bermimpi menjadi seorang komedian. Arthur hidup di Gotham City yang penuh dengan kesulitan dan ketidakadilan sosial. Ia mengalami kesulitan emosional dan psikologis yang berat, sementara masyarakat dan orang-orang di sekitarnya terus memperlakukan dirinya dengan hina.',NULL,1,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,'2025-01-03T16:35:30.299Z',NULL),
	(NULL,'Joker','/uploads\\image-1735922100114.jpg',2019,NULL,'Joker (2019), disutradarai oleh Todd Phillips, adalah sebuah film psikologis yang mengisahkan asal-usul karakter ikonik Joker, musuh bebuyutan Batman. Film ini berfokus pada Arthur Fleck, seorang pria yang bekerja sebagai badut dan bermimpi menjadi seorang komedian. Arthur hidup di Gotham City yang penuh dengan kesulitan dan ketidakadilan sosial. Ia mengalami kesulitan emosional dan psikologis yang berat, sementara masyarakat dan orang-orang di sekitarnya terus memperlakukan dirinya dengan hina.',NULL,1,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,'2025-01-03T16:35:30.299Z'),
	(NULL,'Joker','/uploads\\image-1735922100114.jpg',2019,NULL,'Joker (2019), disutradarai oleh Todd Phillips, adalah sebuah film psikologis yang mengisahkan asal-usul karakter ikonik Joker, musuh bebuyutan Batman. Film ini berfokus pada Arthur Fleck, seorang pria yang bekerja sebagai badut dan bermimpi menjadi seorang komedian. Arthur hidup di Gotham City yang penuh dengan kesulitan dan ketidakadilan sosial. Ia mengalami kesulitan emosional dan psikologis yang berat, sementara masyarakat dan orang-orang di sekitarnya terus memperlakukan dirinya dengan hina.',NULL,1,NULL,'2025-01-03T16:35:00.193Z',NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Joker','/uploads\\image-1735922100114.jpg',2019,NULL,'Joker (2019), disutradarai oleh Todd Phillips, adalah sebuah film psikologis yang mengisahkan asal-usul karakter ikonik Joker, musuh bebuyutan Batman. Film ini berfokus pada Arthur Fleck, seorang pria yang bekerja sebagai badut dan bermimpi menjadi seorang komedian. Arthur hidup di Gotham City yang penuh dengan kesulitan dan ketidakadilan sosial. Ia mengalami kesulitan emosional dan psikologis yang berat, sementara masyarakat dan orang-orang di sekitarnya terus memperlakukan dirinya dengan hina.',NULL,1,NULL,NULL,'2025-01-03T16:35:30.299Z',NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Joker','/uploads\\image-1735922100114.jpg',2019,NULL,'Joker (2019), disutradarai oleh Todd Phillips, adalah sebuah film psikologis yang mengisahkan asal-usul karakter ikonik Joker, musuh bebuyutan Batman. Film ini berfokus pada Arthur Fleck, seorang pria yang bekerja sebagai badut dan bermimpi menjadi seorang komedian. Arthur hidup di Gotham City yang penuh dengan kesulitan dan ketidakadilan sosial. Ia mengalami kesulitan emosional dan psikologis yang berat, sementara masyarakat dan orang-orang di sekitarnya terus memperlakukan dirinya dengan hina.',NULL,1,NULL,NULL,NULL,1,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	('6778134d7e8e51503fb9e977',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Culpa Mia','/uploads\\image-1735922509267.jpg',2023,'67780e647e8e51503fb9e8f6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Culpa Mia','/uploads\\image-1735922509267.jpg',2023,NULL,'Cupla Mía (2023) adalah sebuah film drama romantis Spanyol yang diangkat dari novel karya Mercedes Ron. Film ini mengisahkan tentang Noah, seorang gadis remaja yang terpaksa pindah ke rumah ayahnya yang kaya dan baru menikah dengan seorang wanita bernama Nina. Noah merasa terasing di lingkungan barunya, tetapi keadaan semakin rumit saat dia mulai jatuh cinta pada Nick, anak tiri ayahnya yang sombong dan misterius.','Nicole Wallace',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Culpa Mia','/uploads\\image-1735922509267.jpg',2023,NULL,'Cupla Mía (2023) adalah sebuah film drama romantis Spanyol yang diangkat dari novel karya Mercedes Ron. Film ini mengisahkan tentang Noah, seorang gadis remaja yang terpaksa pindah ke rumah ayahnya yang kaya dan baru menikah dengan seorang wanita bernama Nina. Noah merasa terasing di lingkungan barunya, tetapi keadaan semakin rumit saat dia mulai jatuh cinta pada Nick, anak tiri ayahnya yang sombong dan misterius.','Gabriel Guevara',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Culpa Mia','/uploads\\image-1735922509267.jpg',2023,NULL,'Cupla Mía (2023) adalah sebuah film drama romantis Spanyol yang diangkat dari novel karya Mercedes Ron. Film ini mengisahkan tentang Noah, seorang gadis remaja yang terpaksa pindah ke rumah ayahnya yang kaya dan baru menikah dengan seorang wanita bernama Nina. Noah merasa terasing di lingkungan barunya, tetapi keadaan semakin rumit saat dia mulai jatuh cinta pada Nick, anak tiri ayahnya yang sombong dan misterius.',NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Culpa Mia','/uploads\\image-1735922509267.jpg',2023,NULL,'Cupla Mía (2023) adalah sebuah film drama romantis Spanyol yang diangkat dari novel karya Mercedes Ron. Film ini mengisahkan tentang Noah, seorang gadis remaja yang terpaksa pindah ke rumah ayahnya yang kaya dan baru menikah dengan seorang wanita bernama Nina. Noah merasa terasing di lingkungan barunya, tetapi keadaan semakin rumit saat dia mulai jatuh cinta pada Nick, anak tiri ayahnya yang sombong dan misterius.',NULL,0,'[]','2025-01-03T16:41:49.348Z',NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Culpa Mia','/uploads\\image-1735922509267.jpg',2023,NULL,'Cupla Mía (2023) adalah sebuah film drama romantis Spanyol yang diangkat dari novel karya Mercedes Ron. Film ini mengisahkan tentang Noah, seorang gadis remaja yang terpaksa pindah ke rumah ayahnya yang kaya dan baru menikah dengan seorang wanita bernama Nina. Noah merasa terasing di lingkungan barunya, tetapi keadaan semakin rumit saat dia mulai jatuh cinta pada Nick, anak tiri ayahnya yang sombong dan misterius.',NULL,0,'[]',NULL,'2025-01-03T16:41:49.348Z',NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Culpa Mia','/uploads\\image-1735922509267.jpg',2023,NULL,'Cupla Mía (2023) adalah sebuah film drama romantis Spanyol yang diangkat dari novel karya Mercedes Ron. Film ini mengisahkan tentang Noah, seorang gadis remaja yang terpaksa pindah ke rumah ayahnya yang kaya dan baru menikah dengan seorang wanita bernama Nina. Noah merasa terasing di lingkungan barunya, tetapi keadaan semakin rumit saat dia mulai jatuh cinta pada Nick, anak tiri ayahnya yang sombong dan misterius.',NULL,0,'[]',NULL,NULL,0,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	('6778170e7e8e51503fb9ea0e',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Babylon','/uploads\\image-1735923470040.jpg',2022,'67780e677e8e51503fb9e8fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Babylon','/uploads\\image-1735923470040.jpg',2022,NULL,'Babylon adalah film drama epik yang disutradarai oleh Damien Chazelle, berlatar belakang industri perfilman Hollywood pada masa transisi dari era film bisu ke era film bersuara pada akhir tahun 1920-an. Film ini menggambarkan kehidupan glamor dan penuh kontroversi di dunia perfilman pada masa tersebut.

Cerita mengikuti beberapa karakter utama yang berada di puncak kehidupan sosial dan profesional mereka namun terjerumus dalam kehidupan yang penuh dengan skandal, pesta liar, alkohol, dan kejatuhan moral. Di tengah ketenaran yang meroket, mereka menghadapi perubahan drastis dalam industri film, pergeseran budaya, serta dampak dari ketenaran yang memudar.','Manny Torres',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Babylon','/uploads\\image-1735923470040.jpg',2022,NULL,'Babylon adalah film drama epik yang disutradarai oleh Damien Chazelle, berlatar belakang industri perfilman Hollywood pada masa transisi dari era film bisu ke era film bersuara pada akhir tahun 1920-an. Film ini menggambarkan kehidupan glamor dan penuh kontroversi di dunia perfilman pada masa tersebut.

Cerita mengikuti beberapa karakter utama yang berada di puncak kehidupan sosial dan profesional mereka namun terjerumus dalam kehidupan yang penuh dengan skandal, pesta liar, alkohol, dan kejatuhan moral. Di tengah ketenaran yang meroket, mereka menghadapi perubahan drastis dalam industri film, pergeseran budaya, serta dampak dari ketenaran yang memudar.','Nellie LaRoy',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Babylon','/uploads\\image-1735923470040.jpg',2022,NULL,'Babylon adalah film drama epik yang disutradarai oleh Damien Chazelle, berlatar belakang industri perfilman Hollywood pada masa transisi dari era film bisu ke era film bersuara pada akhir tahun 1920-an. Film ini menggambarkan kehidupan glamor dan penuh kontroversi di dunia perfilman pada masa tersebut.

Cerita mengikuti beberapa karakter utama yang berada di puncak kehidupan sosial dan profesional mereka namun terjerumus dalam kehidupan yang penuh dengan skandal, pesta liar, alkohol, dan kejatuhan moral. Di tengah ketenaran yang meroket, mereka menghadapi perubahan drastis dalam industri film, pergeseran budaya, serta dampak dari ketenaran yang memudar.',NULL,0,'[]','2025-01-03T16:57:50.102Z',NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Babylon','/uploads\\image-1735923470040.jpg',2022,NULL,'Babylon adalah film drama epik yang disutradarai oleh Damien Chazelle, berlatar belakang industri perfilman Hollywood pada masa transisi dari era film bisu ke era film bersuara pada akhir tahun 1920-an. Film ini menggambarkan kehidupan glamor dan penuh kontroversi di dunia perfilman pada masa tersebut.

Cerita mengikuti beberapa karakter utama yang berada di puncak kehidupan sosial dan profesional mereka namun terjerumus dalam kehidupan yang penuh dengan skandal, pesta liar, alkohol, dan kejatuhan moral. Di tengah ketenaran yang meroket, mereka menghadapi perubahan drastis dalam industri film, pergeseran budaya, serta dampak dari ketenaran yang memudar.',NULL,0,'[]',NULL,'2025-01-03T16:57:50.102Z',NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Babylon','/uploads\\image-1735923470040.jpg',2022,NULL,'Babylon adalah film drama epik yang disutradarai oleh Damien Chazelle, berlatar belakang industri perfilman Hollywood pada masa transisi dari era film bisu ke era film bersuara pada akhir tahun 1920-an. Film ini menggambarkan kehidupan glamor dan penuh kontroversi di dunia perfilman pada masa tersebut.

Cerita mengikuti beberapa karakter utama yang berada di puncak kehidupan sosial dan profesional mereka namun terjerumus dalam kehidupan yang penuh dengan skandal, pesta liar, alkohol, dan kejatuhan moral. Di tengah ketenaran yang meroket, mereka menghadapi perubahan drastis dalam industri film, pergeseran budaya, serta dampak dari ketenaran yang memudar.',NULL,0,'[]',NULL,NULL,0,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	('6778184a7e8e51503fb9ea2f',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'The School for Good and Evil ','/uploads\\image-1735923786909.jpg',2022,'67780e6c7e8e51503fb9e900',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'The School for Good and Evil ','/uploads\\image-1735923786909.jpg',2022,NULL,'The School for Good and Evil adalah film fantasi yang disutradarai oleh Paul Feig, berdasarkan novel dengan judul yang sama karya Soman Chainani. Film ini mengisahkan tentang dua gadis, Sophie dan Agatha, yang terpilih untuk bersekolah di The School for Good and Evil, sebuah sekolah yang melatih anak-anak untuk menjadi pahlawan atau penjahat dalam cerita dongeng.','Sophia Anne Caruso',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'The School for Good and Evil ','/uploads\\image-1735923786909.jpg',2022,NULL,'The School for Good and Evil adalah film fantasi yang disutradarai oleh Paul Feig, berdasarkan novel dengan judul yang sama karya Soman Chainani. Film ini mengisahkan tentang dua gadis, Sophie dan Agatha, yang terpilih untuk bersekolah di The School for Good and Evil, sebuah sekolah yang melatih anak-anak untuk menjadi pahlawan atau penjahat dalam cerita dongeng.','Sofia Wylie',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'The School for Good and Evil ','/uploads\\image-1735923786909.jpg',2022,NULL,'The School for Good and Evil adalah film fantasi yang disutradarai oleh Paul Feig, berdasarkan novel dengan judul yang sama karya Soman Chainani. Film ini mengisahkan tentang dua gadis, Sophie dan Agatha, yang terpilih untuk bersekolah di The School for Good and Evil, sebuah sekolah yang melatih anak-anak untuk menjadi pahlawan atau penjahat dalam cerita dongeng.',NULL,0,'[]','2025-01-03T17:03:06.980Z',NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'The School for Good and Evil ','/uploads\\image-1735923786909.jpg',2022,NULL,'The School for Good and Evil adalah film fantasi yang disutradarai oleh Paul Feig, berdasarkan novel dengan judul yang sama karya Soman Chainani. Film ini mengisahkan tentang dua gadis, Sophie dan Agatha, yang terpilih untuk bersekolah di The School for Good and Evil, sebuah sekolah yang melatih anak-anak untuk menjadi pahlawan atau penjahat dalam cerita dongeng.',NULL,0,'[]',NULL,'2025-01-03T17:03:06.980Z',NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'The School for Good and Evil ','/uploads\\image-1735923786909.jpg',2022,NULL,'The School for Good and Evil adalah film fantasi yang disutradarai oleh Paul Feig, berdasarkan novel dengan judul yang sama karya Soman Chainani. Film ini mengisahkan tentang dua gadis, Sophie dan Agatha, yang terpilih untuk bersekolah di The School for Good and Evil, sebuah sekolah yang melatih anak-anak untuk menjadi pahlawan atau penjahat dalam cerita dongeng.',NULL,0,'[]',NULL,NULL,0,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	('6778190d7e8e51503fb9ea50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,'67780e7e7e8e51503fb9e905',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.','Dwayne Johnson',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.','Kevin Hart ',NULL,NULL,NULL,NULL,NULL,'Farhan',0,'musuh batman',NULL,NULL,NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,NULL,NULL,'FarhanVirenze',0,'Bagus','6777f5f5bc3162bf784c3646',NULL,NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,NULL,NULL,'FarhanVirenze',0,'Bagus',NULL,'6778e8596db65fb33a1f7260',NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,NULL,NULL,'FarhanVirenze',0,'Bagus',NULL,NULL,'2025-01-04T07:50:49.843Z',NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,NULL,NULL,'FarhanVirenze',0,'Bagus',NULL,NULL,NULL,'2025-01-04T07:50:49.843Z'),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,NULL,NULL,'haris',0,'film jelek','677808807e8e51503fb9e8ab',NULL,NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,'677b4a7ceada3570d86810a0',NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,'2025-01-06T03:14:04.228Z',NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,'2025-01-06T03:14:04.228Z'),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,'2025-01-03T17:06:21.571Z',NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,'2025-01-06T03:14:04.230Z',NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Jumanji','/uploads\\image-1735923981447.jpg',2017,NULL,'Jumanji: Welcome to the Jungle adalah film petualangan komedi yang disutradarai oleh Jake Kasdan, dan merupakan sekuel dari film Jumanji (1995). Film ini mengisahkan empat remaja yang terjebak dalam dunia permainan video Jumanji, yang mengubah mereka menjadi karakter-karakter fiksi dengan kemampuan dan kekuatan tertentu.',NULL,2,NULL,NULL,NULL,2,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	('677b8062e9772b3768e9dfcd',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Anabelle 3','/uploads\\image-1737034113206.jpg',2018,'6777f96abc3162bf784c3659',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Anabelle 3','/uploads\\image-1737034113206.jpg',2018,NULL,'Annabelle: Creation adalah prekuel dari film horor Annabelle (2014) yang disutradarai oleh David F. Sandberg. Film ini mengisahkan asal-usul boneka Annabelle yang menyeramkan.

Cerita dimulai dengan pembuat boneka Samuel Mullins (Anthony LaPaglia) dan istrinya, Esther (Miranda Otto), yang hidup bahagia bersama putri mereka, Bee. Namun, kebahagiaan itu berubah menjadi tragedi ketika Bee tewas dalam kecelakaan mobil. Dalam kesedihan mendalam, Samuel dan Esther membuat kesepakatan dengan entitas gaib untuk "bertemu kembali" dengan Bee. Sayangnya, entitas tersebut malah merasuki boneka buatan Samuel, yang kemudian dikenal sebagai Annabelle.','Anthony LaPaglia',NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Anabelle 3','/uploads\\image-1737034113206.jpg',2018,NULL,'Annabelle: Creation adalah prekuel dari film horor Annabelle (2014) yang disutradarai oleh David F. Sandberg. Film ini mengisahkan asal-usul boneka Annabelle yang menyeramkan.

Cerita dimulai dengan pembuat boneka Samuel Mullins (Anthony LaPaglia) dan istrinya, Esther (Miranda Otto), yang hidup bahagia bersama putri mereka, Bee. Namun, kebahagiaan itu berubah menjadi tragedi ketika Bee tewas dalam kecelakaan mobil. Dalam kesedihan mendalam, Samuel dan Esther membuat kesepakatan dengan entitas gaib untuk "bertemu kembali" dengan Bee. Sayangnya, entitas tersebut malah merasuki boneka buatan Samuel, yang kemudian dikenal sebagai Annabelle.','Miranda Otto',NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Anabelle 3','/uploads\\image-1737034113206.jpg',2018,NULL,'Annabelle: Creation adalah prekuel dari film horor Annabelle (2014) yang disutradarai oleh David F. Sandberg. Film ini mengisahkan asal-usul boneka Annabelle yang menyeramkan.

Cerita dimulai dengan pembuat boneka Samuel Mullins (Anthony LaPaglia) dan istrinya, Esther (Miranda Otto), yang hidup bahagia bersama putri mereka, Bee. Namun, kebahagiaan itu berubah menjadi tragedi ketika Bee tewas dalam kecelakaan mobil. Dalam kesedihan mendalam, Samuel dan Esther membuat kesepakatan dengan entitas gaib untuk "bertemu kembali" dengan Bee. Sayangnya, entitas tersebut malah merasuki boneka buatan Samuel, yang kemudian dikenal sebagai Annabelle.',NULL,0,'[]','2025-01-06T07:04:02.839Z',NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Anabelle 3','/uploads\\image-1737034113206.jpg',2018,NULL,'Annabelle: Creation adalah prekuel dari film horor Annabelle (2014) yang disutradarai oleh David F. Sandberg. Film ini mengisahkan asal-usul boneka Annabelle yang menyeramkan.

Cerita dimulai dengan pembuat boneka Samuel Mullins (Anthony LaPaglia) dan istrinya, Esther (Miranda Otto), yang hidup bahagia bersama putri mereka, Bee. Namun, kebahagiaan itu berubah menjadi tragedi ketika Bee tewas dalam kecelakaan mobil. Dalam kesedihan mendalam, Samuel dan Esther membuat kesepakatan dengan entitas gaib untuk "bertemu kembali" dengan Bee. Sayangnya, entitas tersebut malah merasuki boneka buatan Samuel, yang kemudian dikenal sebagai Annabelle.',NULL,0,'[]',NULL,'2025-01-16T13:28:33.352Z',NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Anabelle 3','/uploads\\image-1737034113206.jpg',2018,NULL,'Annabelle: Creation adalah prekuel dari film horor Annabelle (2014) yang disutradarai oleh David F. Sandberg. Film ini mengisahkan asal-usul boneka Annabelle yang menyeramkan.

Cerita dimulai dengan pembuat boneka Samuel Mullins (Anthony LaPaglia) dan istrinya, Esther (Miranda Otto), yang hidup bahagia bersama putri mereka, Bee. Namun, kebahagiaan itu berubah menjadi tragedi ketika Bee tewas dalam kecelakaan mobil. Dalam kesedihan mendalam, Samuel dan Esther membuat kesepakatan dengan entitas gaib untuk "bertemu kembali" dengan Bee. Sayangnya, entitas tersebut malah merasuki boneka buatan Samuel, yang kemudian dikenal sebagai Annabelle.',NULL,0,'[]',NULL,NULL,0,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	('677f297eb2855c339529d487',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Cinderella','/uploads\\image-1737033846305.jpg',2015,'67780e677e8e51503fb9e8fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Cinderella','/uploads\\image-1737033846305.jpg',2015,NULL,'Cinderella adalah kisah klasik tentang seorang gadis muda yang hidup dalam penderitaan namun tetap memiliki hati yang baik. Setelah kehilangan kedua orang tuanya, Cinderella tinggal bersama ibu tiri yang kejam dan dua saudara tiri yang memperlakukannya seperti pembantu. Ia dipaksa melakukan semua pekerjaan rumah tangga dan sering dihina karena penampilannya yang sederhana.','Lily James',NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Cinderella','/uploads\\image-1737033846305.jpg',2015,NULL,'Cinderella adalah kisah klasik tentang seorang gadis muda yang hidup dalam penderitaan namun tetap memiliki hati yang baik. Setelah kehilangan kedua orang tuanya, Cinderella tinggal bersama ibu tiri yang kejam dan dua saudara tiri yang memperlakukannya seperti pembantu. Ia dipaksa melakukan semua pekerjaan rumah tangga dan sering dihina karena penampilannya yang sederhana.','Richard Madden',NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Cinderella','/uploads\\image-1737033846305.jpg',2015,NULL,'Cinderella adalah kisah klasik tentang seorang gadis muda yang hidup dalam penderitaan namun tetap memiliki hati yang baik. Setelah kehilangan kedua orang tuanya, Cinderella tinggal bersama ibu tiri yang kejam dan dua saudara tiri yang memperlakukannya seperti pembantu. Ia dipaksa melakukan semua pekerjaan rumah tangga dan sering dihina karena penampilannya yang sederhana.',NULL,0,'[]','2025-01-09T01:42:22.064Z',NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Cinderella','/uploads\\image-1737033846305.jpg',2015,NULL,'Cinderella adalah kisah klasik tentang seorang gadis muda yang hidup dalam penderitaan namun tetap memiliki hati yang baik. Setelah kehilangan kedua orang tuanya, Cinderella tinggal bersama ibu tiri yang kejam dan dua saudara tiri yang memperlakukannya seperti pembantu. Ia dipaksa melakukan semua pekerjaan rumah tangga dan sering dihina karena penampilannya yang sederhana.',NULL,0,'[]',NULL,'2025-01-16T13:24:06.356Z',NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Cinderella','/uploads\\image-1737033846305.jpg',2015,NULL,'Cinderella adalah kisah klasik tentang seorang gadis muda yang hidup dalam penderitaan namun tetap memiliki hati yang baik. Setelah kehilangan kedua orang tuanya, Cinderella tinggal bersama ibu tiri yang kejam dan dua saudara tiri yang memperlakukannya seperti pembantu. Ia dipaksa melakukan semua pekerjaan rumah tangga dan sering dihina karena penampilannya yang sederhana.',NULL,0,'[]',NULL,NULL,0,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	('67890827afb1296640725017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'upin ipin','/uploads\\image-1737033767340.jpg',2020,'67780e997e8e51503fb9e90a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'upin ipin','/uploads\\image-1737033767340.jpg',2020,NULL,'Penguasa Elemental','yaya',NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'upin ipin','/uploads\\image-1737033767340.jpg',2020,NULL,'Penguasa Elemental','ying',NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'upin ipin','/uploads\\image-1737033767340.jpg',2020,NULL,'Penguasa Elemental',NULL,0,'[]','2025-01-16T13:22:47.400Z',NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'upin ipin','/uploads\\image-1737033767340.jpg',2020,NULL,'Penguasa Elemental',NULL,0,'[]',NULL,'2025-01-16T13:22:47.400Z',NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'upin ipin','/uploads\\image-1737033767340.jpg',2020,NULL,'Penguasa Elemental',NULL,0,'[]',NULL,NULL,0,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	('67891504afb12966407250d5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Boboiboy','/uploads\\image-1737037060786.jpg',2024,'67780e997e8e51503fb9e90a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Boboiboy','/uploads\\image-1737037060786.jpg',2024,NULL,'Penguasa Elemental','yaya',NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Boboiboy','/uploads\\image-1737037060786.jpg',2024,NULL,'Penguasa Elemental','ying',NULL,NULL,NULL,NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Boboiboy','/uploads\\image-1737037060786.jpg',2024,NULL,'Penguasa Elemental',NULL,0,'[]','2025-01-16T14:17:40.835Z',NULL,NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Boboiboy','/uploads\\image-1737037060786.jpg',2024,NULL,'Penguasa Elemental',NULL,0,'[]',NULL,'2025-01-16T14:17:40.835Z',NULL,'haris',0,'film jelek',NULL,NULL,NULL,NULL),
	(NULL,'Boboiboy','/uploads\\image-1737037060786.jpg',2024,NULL,'Penguasa Elemental',NULL,0,'[]',NULL,NULL,0,'haris',0,'film jelek',NULL,NULL,NULL,NULL);



CREATE TABLE IF NOT EXISTS `Netflixo_youtube_genres` (
    `id_oid` VARCHAR(24) CHARACTER SET utf8,
    `name` VARCHAR(15) CHARACTER SET utf8,
    `v` INT
);
INSERT INTO `Netflixo_youtube_genres` VALUES ('6777f96abc3162bf784c3659',NULL,NULL),
	(NULL,'Horror',0),
	('6777fb0bbc3162bf784c367c',NULL,NULL),
	(NULL,'Action',0),
	('67780e647e8e51503fb9e8f6',NULL,NULL),
	(NULL,'Romance',0),
	('67780e677e8e51503fb9e8fb',NULL,NULL),
	(NULL,'Drama',0),
	('67780e6c7e8e51503fb9e900',NULL,NULL),
	(NULL,'Fantasy',0),
	('67780e7e7e8e51503fb9e905',NULL,NULL),
	(NULL,'Adventure',0),
	('67780e997e8e51503fb9e90a',NULL,NULL),
	(NULL,'Comedy',0),
	('67780ea27e8e51503fb9e90f',NULL,NULL),
	(NULL,'Thriller',0),
	('67780ec77e8e51503fb9e91a',NULL,NULL),
	(NULL,'Science fiction',0),
	('6787f25a515b2d6942001f0f',NULL,NULL),
	(NULL,'Game',0);


CREATE TABLE IF NOT EXISTS `Netflixo_youtube_users` (
    `id_oid` VARCHAR(24) CHARACTER SET utf8,
    `username` VARCHAR(13) CHARACTER SET utf8,
    `email` VARCHAR(25) CHARACTER SET utf8,
    `password` VARCHAR(60) CHARACTER SET utf8,
    `isAdmin` VARCHAR(5) CHARACTER SET utf8,
    `createdAt_date` VARCHAR(24) CHARACTER SET utf8,
    `updatedAt_date` VARCHAR(24) CHARACTER SET utf8,
    `v` INT
);
INSERT INTO `Netflixo_youtube_users` VALUES ('6777f5f5bc3162bf784c3646',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'FarhanVirenze','farhanvirenze18@gmail.com','$2a$10$bkJizBLK9xBTjJLyOEw05Oy4spwycEsPTvldKAnT/G8L44SGqbJWe','True','2025-01-03T14:36:37.935Z',NULL,NULL),
	(NULL,'FarhanVirenze','farhanvirenze18@gmail.com','$2a$10$bkJizBLK9xBTjJLyOEw05Oy4spwycEsPTvldKAnT/G8L44SGqbJWe','True',NULL,'2025-01-15T15:55:21.486Z',NULL),
	(NULL,'FarhanVirenze','farhanvirenze18@gmail.com','$2a$10$bkJizBLK9xBTjJLyOEw05Oy4spwycEsPTvldKAnT/G8L44SGqbJWe','True',NULL,NULL,0),
	('67780248a63ae07a43d1dcd4',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'iqsha','iqsha@gmail.com','$2a$10$2YkBVZYlfHe8kjjn9zY1/.AH4dcYAoqj4kY4f.nSuFSlrcENg0Za.','False','2025-01-03T15:29:12.526Z',NULL,NULL),
	(NULL,'iqsha','iqsha@gmail.com','$2a$10$2YkBVZYlfHe8kjjn9zY1/.AH4dcYAoqj4kY4f.nSuFSlrcENg0Za.','False',NULL,'2025-01-03T15:29:12.526Z',NULL),
	(NULL,'iqsha','iqsha@gmail.com','$2a$10$2YkBVZYlfHe8kjjn9zY1/.AH4dcYAoqj4kY4f.nSuFSlrcENg0Za.','False',NULL,NULL,0),
	('677808807e8e51503fb9e8ab',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'haris','haris@gmail.com','$2a$10$X4HJmLvx6kSB7bUqc1TKe.ZM9eu02YF9cyhjAhR116fzHuNGaVk2K','True','2025-01-03T15:55:44.022Z',NULL,NULL),
	(NULL,'haris','haris@gmail.com','$2a$10$X4HJmLvx6kSB7bUqc1TKe.ZM9eu02YF9cyhjAhR116fzHuNGaVk2K','True',NULL,'2025-01-03T15:55:44.022Z',NULL),
	(NULL,'haris','haris@gmail.com','$2a$10$X4HJmLvx6kSB7bUqc1TKe.ZM9eu02YF9cyhjAhR116fzHuNGaVk2K','True',NULL,NULL,0),
	('6778c1aa6db65fb33a1f709b',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Agus','Agus@gmail.com','$2a$10$8nDATZ6J1kmrMs6KOOcV3.kEfJOhl7Sri5rZ7mbQPLhIFM7d4SKNG','False','2025-01-04T05:05:46.994Z',NULL,NULL),
	(NULL,'Agus','Agus@gmail.com','$2a$10$8nDATZ6J1kmrMs6KOOcV3.kEfJOhl7Sri5rZ7mbQPLhIFM7d4SKNG','False',NULL,'2025-01-04T05:05:46.994Z',NULL),
	(NULL,'Agus','Agus@gmail.com','$2a$10$8nDATZ6J1kmrMs6KOOcV3.kEfJOhl7Sri5rZ7mbQPLhIFM7d4SKNG','False',NULL,NULL,0),
	('677b845fe9772b3768e9e046',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'Titanic','titanic@gmail.com','$2a$10$M8xJU2fg.0mO0GZg7zx.4eRIbqxjYIwNaNH1Nj5X1RPcYdNaTRYVm','False','2025-01-06T07:21:03.009Z',NULL,NULL),
	(NULL,'Titanic','titanic@gmail.com','$2a$10$M8xJU2fg.0mO0GZg7zx.4eRIbqxjYIwNaNH1Nj5X1RPcYdNaTRYVm','False',NULL,'2025-01-06T07:21:03.009Z',NULL),
	(NULL,'Titanic','titanic@gmail.com','$2a$10$M8xJU2fg.0mO0GZg7zx.4eRIbqxjYIwNaNH1Nj5X1RPcYdNaTRYVm','False',NULL,NULL,0),
	('677b864bd1ebf79e050816f8',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'bintang','bintang@gmail.com','$2a$10$QxJe0WuWlFgvmw3cFAUSBOZ/VejCFUzHIDUGIJ3oRHWKg/bva8WfW','False','2025-01-06T07:29:15.451Z',NULL,NULL),
	(NULL,'bintang','bintang@gmail.com','$2a$10$QxJe0WuWlFgvmw3cFAUSBOZ/VejCFUzHIDUGIJ3oRHWKg/bva8WfW','False',NULL,'2025-01-06T07:29:15.451Z',NULL),
	(NULL,'bintang','bintang@gmail.com','$2a$10$QxJe0WuWlFgvmw3cFAUSBOZ/VejCFUzHIDUGIJ3oRHWKg/bva8WfW','False',NULL,NULL,0),
	('677f23be4e155aa225827e7a',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'kevin','kevin@gmail.com','$2a$10$3v/4SXxlo/Hrbs2jDDsqhOe.qP2d4s8W//ovNxcoOxFNRlTOKDjnC','True','2025-01-09T01:17:50.463Z',NULL,NULL),
	(NULL,'kevin','kevin@gmail.com','$2a$10$3v/4SXxlo/Hrbs2jDDsqhOe.qP2d4s8W//ovNxcoOxFNRlTOKDjnC','True',NULL,'2025-01-09T01:17:50.463Z',NULL),
	(NULL,'kevin','kevin@gmail.com','$2a$10$3v/4SXxlo/Hrbs2jDDsqhOe.qP2d4s8W//ovNxcoOxFNRlTOKDjnC','True',NULL,NULL,0),
	('677f249a4e155aa225827e9c',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'buaya','buaya@gmail.com','$2a$10$J6O0mZ1HyI9ftQIFsyIi7.IKdK65KlyLDqQDIFtpcJNZZ77R0HHp2','False','2025-01-09T01:21:30.841Z',NULL,NULL),
	(NULL,'buaya','buaya@gmail.com','$2a$10$J6O0mZ1HyI9ftQIFsyIi7.IKdK65KlyLDqQDIFtpcJNZZ77R0HHp2','False',NULL,'2025-01-09T01:21:30.841Z',NULL),
	(NULL,'buaya','buaya@gmail.com','$2a$10$J6O0mZ1HyI9ftQIFsyIi7.IKdK65KlyLDqQDIFtpcJNZZ77R0HHp2','False',NULL,NULL,0),
	('677f276686d6dd3887769d76',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'ngawi','ngawi@gmail.com','$2a$10$lmTCOBqkuPmrC18JG2DsmOM/cMEQAD1YlQiGeNyhFQztPvzOpBlN.','True','2025-01-09T01:33:26.816Z',NULL,NULL),
	(NULL,'ngawi','ngawi@gmail.com','$2a$10$lmTCOBqkuPmrC18JG2DsmOM/cMEQAD1YlQiGeNyhFQztPvzOpBlN.','True',NULL,'2025-01-09T01:33:26.816Z',NULL),
	(NULL,'ngawi','ngawi@gmail.com','$2a$10$lmTCOBqkuPmrC18JG2DsmOM/cMEQAD1YlQiGeNyhFQztPvzOpBlN.','True',NULL,NULL,0),
	('67890430afb1296640724fe6',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'baba','baba@gmail.com','$2a$10$95zGya8VCa.th5AaxBD3kuzGTKea06Jj.O8XstB9rQ3cahNsR5AxW','False','2025-01-16T13:05:52.340Z',NULL,NULL),
	(NULL,'baba','baba@gmail.com','$2a$10$95zGya8VCa.th5AaxBD3kuzGTKea06Jj.O8XstB9rQ3cahNsR5AxW','False',NULL,'2025-01-16T13:05:52.340Z',NULL),
	(NULL,'baba','baba@gmail.com','$2a$10$95zGya8VCa.th5AaxBD3kuzGTKea06Jj.O8XstB9rQ3cahNsR5AxW','False',NULL,NULL,0),
	('67891328afb1296640725098',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,'bibi','bibi@gmail.com','$2a$10$EaaI63jnqSDwRNJsq.mJz.t1d8Xh9UIBGd4EfYQqqpFhNJ7fqABvW','False','2025-01-16T14:09:44.806Z',NULL,NULL),
	(NULL,'bibi','bibi@gmail.com','$2a$10$EaaI63jnqSDwRNJsq.mJz.t1d8Xh9UIBGd4EfYQqqpFhNJ7fqABvW','False',NULL,'2025-01-16T14:09:44.806Z',NULL),
	(NULL,'bibi','bibi@gmail.com','$2a$10$EaaI63jnqSDwRNJsq.mJz.t1d8Xh9UIBGd4EfYQqqpFhNJ7fqABvW','False',NULL,NULL,0);
